# production parameters
parameters:
    log_level:  DEBUG
    #--- TimeZone: UTC, Europe/Kiev...
    timezone: UTC

    locale: nl

    # debug: true, false ---
    debug: true

    # host url for local testing ---
    url_test: 'http://www.marionleblanc.nl'

    # database parameters ---
    db.driver:   'pdo_mysql'
    db.host:     'mysql.marionleblanc.nl'
    db.dbname:   'marionleblancnl'
    db.user:     'marionleblancnl'
    db.password: 'x2D3SvY0P2O'
    db.charset:  'utf8'
    db.dbtype:   'mysql'
    db.port:     '3306'

    # developer mail ---
    developer_mail: 'dev@mail.com'

    # email parameters ---
    mail.host: 'smtp.vevida.com'
    mail.port: 25
    mail.username: 'art@marionleblanc.nl'
    mail.noreply: 'noreply@marionleblanc.nl'
    mail.password: 'Jonneke22!' # to do: encryption
    mail.encryption: 'tls' # ('tls', 'ssl', or null)
    mail.auth_mode: 'login' # ('plain', 'login', 'cram-md5', or null)
    mail.disable_delivery:  true
